version: 1.0.0
image: Visual Studio 2015
build_script:
- ps: ./Build.ps1
test: off
deploy:
  - provider: NuGet
    api_key:
      secure: BSOZdVuP4kYGBHI+9UHHsmTinFLVyzvsJy1HDMbEok9URhK1Fg7yOWLG3mk5AahQ
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

  - provider: GitHub
    release: v$(GitVersion_SemVer)
    description: 'TwentyTwenty.Mvc'
    auth_token:
      secure: fd/+7iqe48Pb5+TSjRLgl4uEP4FvKjAv8xs0MI+cgYPJ3QX2/cBdfJt2E6fbwHFr
    artifact: /.*\.nupkg/
    draft: true
    on:    
      appveyor_repo_tag: true        # deploy on tag push only