version: 1.0.{build}
image: Visual Studio 2022
install:
  - choco install gitversion.portable
before_build:
  - cmd: dotnet --version
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - cmd: dotnet restore ./src/TwentyTwenty.Mvc/TwentyTwenty.Mvc.csproj
build_script:
  - cmd: dotnet pack ./src/TwentyTwenty.Mvc/TwentyTwenty.Mvc.csproj --no-restore -c Release -p:PackageVersion=%GitVersion_NuGetVersion%
test: off
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    api_key:
      secure: 9LiiCtcE3GJ04Z/jp8PzfQxBC9sluCHrRqRX5HQ1tOFdsXDeIn52NKoh+zOhJPcv
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

  - provider: GitHub
    release: "%GitVersion_NuGetVersion%"
    description: 'TwentyTwenty.Mvc'
    auth_token:
      secure: jRySGaPcL/02436nnSFXkVrbKAZHK/lt+djaz2TBts8InPudWVPYY/rqWeSVe3LJGdGXEUV7bBgGbRazdD/UxV2HvB/Gm+Pqzxx4NQA2MvFf8AjqnM0U2KBcitL1Ao1O
    artifact: /.*\.nupkg/
    draft: true
    on:    
      appveyor_repo_tag: true        # deploy on tag push only