version: 1.0.{build}
image: Visual Studio 2019
install:
  - choco install gitversion.portable -pre -y
before_build:
  - cmd: dotnet --version
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - cmd: dotnet restore ./src/TwentyTwenty.Mvc/TwentyTwenty.Mvc.csproj
build_script:
  - cmd: dotnet pack ./src/TwentyTwenty.Mvc/TwentyTwenty.Mvc.csproj --no-restore -c Release /p:SemVer=%GitVersion_NuGetVersion%
test: off
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    api_key:
      secure: zbVLdtBTLzHDiLO1T4O9r6Jj0XthVKRtK1B0EtqWhDpaoF3Iv3smoGB0k0PW1TRB
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

  - provider: GitHub
    release: v$(GitVersion_SemVer)
    description: 'TwentyTwenty.Mvc'
    auth_token:
      secure: fd/+7iqe48Pb5+TSjRLgl4uEP4FvKjAv8xs0MI+cgYPJ3QX2/cBdfJt2E6fbwHFr
    artifact: /.*\.nupkg/
    draft: true
    on:    
      appveyor_repo_tag: true        # deploy on tag push only