version: 1.0.{build}
image: Visual Studio 2022
install:
  - ps: Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1; ./dotnet-install.ps1 -Channel 10.0 -InstallDir 'C:\Program Files\dotnet'
  - dotnet tool install --global GitVersion.Tool
before_build:
  - cmd: dotnet --version
  - ps: dotnet-gitversion /l console /output buildserver
  - cmd: dotnet restore ./src/TwentyTwenty.Mvc/TwentyTwenty.Mvc.csproj
build_script:
  - cmd: dotnet pack ./src/TwentyTwenty.Mvc/TwentyTwenty.Mvc.csproj --no-restore -c Release -p:PackageVersion=%GitVersion_MajorMinorPatch%
test: off
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    api_key:
      secure: XDYUP5FUbfBpSCa5alD/lpMWAj12aomtjy3qwfyr2My5fZnS7NGmg7j7eUA8jZsh
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

  - provider: GitHub
    release: "%GitVersion_MajorMinorPatch%"
    description: 'TwentyTwenty.Mvc'
    auth_token:
      secure: jRySGaPcL/02436nnSFXkf/7wkuamJan+trlbInaAs3NNXCv3S+7IvEiMGvHURPgBBxkMRkB33G0uIeRZ5gQCgSn+Eh2zXORQqSGnWQ0qscw9u5b7OPw3Nyl9/yG2wpq
    artifact: /.*\.nupkg/
    draft: false
    on:    
      appveyor_repo_tag: true        # deploy on tag push only