version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
build_script:
- ps: ./Build.ps1
test: off
deploy:
  - provider: NuGet
    api_key:
      secure: zbVLdtBTLzHDiLO1T4O9r6Jj0XthVKRtK1B0EtqWhDpaoF3Iv3smoGB0k0PW1TRB
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

  - provider: GitHub
    release: v$(GitVersion_SemVer)
    description: 'TwentyTwenty.Mvc'
    auth_token:
      secure: fd/+7iqe48Pb5+TSjRLgl4uEP4FvKjAv8xs0MI+cgYPJ3QX2/cBdfJt2E6fbwHFr
    artifact: /.*\.nupkg/
    draft: true
    on:    
      appveyor_repo_tag: true        # deploy on tag push only